server:
  port: 45678
spring:
  profiles:
    active: dev
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tcc_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
tcc:
  zookeeper:
    nodes: 127.0.0.1:2181
    time-out: 300000
    enable: true
