server:
  port: 45678
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
tcc:
  zookeeper:
    nodes: 127.0.0.1:2181
    time-out: 300000
    enable: true